### ISSUE TITLE
Upgrade the GeBiz code for input and output data to include keyword and username

### ISSUE THREAD

**Issue by steelwolf180** [steelwolf180/BOS#5]
Upgraded the GeBiz code to allow the Keyword.txt to include keyword and username. example below.
- Ipad,Max
- Tablet,Dorry
- Phone,John
- Mobile,Hager

when data is extracted it will also include keyword and username 

![image](https://cloud.githubusercontent.com/assets/6166378/3197316/41fd9f76-ed46-11e3-88c7-904b9661ac16.png)

**Comment by ahboon** [comment]
okay. put the updated packages in the share folder:
Full path:
\btw.local\BTW\BTWWebScrapper\Updates_Put_Here

On 6 June 2014 14:46, Max Ong Zong Bao notifications@github.com wrote:

> Closed #5 https://github.com/steelwolf180/BOS/issues/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/steelwolf180/BOS/issues/5#event-128689973.

## 

Sim Cher Boon
simcherboon123@gmail.com

**Comment by steelwolf180** [comment]
The updated version is located at Github under Gebiz folder. You can
download it and upload it the server
okay. put the updated packages in the share folder:
Full path:
\btw.local\BTW\BTWWebScrapper\Updates_Put_Here

On 6 June 2014 14:46, Max Ong Zong Bao notifications@github.com wrote:

> Closed #5 https://github.com/steelwolf180/BOS/issues/5.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/steelwolf180/BOS/issues/5#event-128689973.

## 

Sim Cher Boon
simcherboon123@gmail.com

**Comment by ahboon** [comment]
Okay.

On Saturday, June 7, 2014, Max Ong Zong Bao notifications@github.com
wrote:

> The updated version is located at Github under Gebiz folder. You can
> download it and upload it the server
> okay. put the updated packages in the share folder:
> Full path:
> \btw.local\BTW\BTWWebScrapper\Updates_Put_Here
> 
> On 6 June 2014 14:46, Max Ong Zong Bao <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > Closed #5 https://github.com/steelwolf180/BOS/issues/5.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/steelwolf180/BOS/issues/5#event-128689973.
> 
> ## 
> 
> Sim Cher Boon
> simcherboon123@gmail.com
> <javascript:_e(%7B%7D,'cvml','simcherboon123@gmail.com');>
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/steelwolf180/BOS/issues/5#issuecomment-45400276.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/steelwolf180/BOS/issues/5#issuecomment-45400595.

## 

Sim Cher Boon
simcherboon123@gmail.com
